Repository innovation-camp/heonchaegjulge, pull requests merged in 2022-08, with the labels that each got.

#1 Chore: develop branch 생성
  .gitignore
  README.md
  app/__init__.py
  app/account.py
  app/article.py
  app/db.py
  app/static/style.css
  app/templates/account/signin.html
  app/templates/account/signup.html
  app/templates/base.html
  app/templates/post/create.html
  app/templates/post/index.html
  requirements.txt
Labels: good first issue

#2 Chore : requirements update
  requirements.txt
Labels: bug

#6 Feat : account signup / signin 구현
  .gitignore
  .idea/misc.xml
  .idea/week_1.iml
  app/__init__.py
  app/constants.py
  app/controller/__init__.py
  app/controller/account.py
  app/controller/article.py
  app/controller/ctr_test.py
  app/decorators/__init__.py
  app/decorators/login_required.py
  app/decorators/templated.py
  app/middleware/__init__.py
  app/middleware/load_logged_in_user.py
  app/static/open-book 2.png
  app/static/signin.css
  app/static/signup.css
  app/templates/account/signin.html
  app/templates/account/signup.html
  app/templates/base.html
  app/templates/error/404.html
  app/templates/head.html
  app/utils.py
  requirements.txt
Labels: enhancement

#9 Feat: logout 기능 추가
  app/controller/account.py
  app/controller/posts.py
  app/templates/navbar.html
  app/templates/post/detail.html
Labels: enhancement

#13 Feat: login logout을 했을 경우 main 페이지로 이동
  README.md
  app/controller/account.py
Labels: enhancement

#17 Fix: account 관련 이슈 해결
  app/controller/account.py
  app/templates/account/signin.html
  app/templates/common/navbar.html
Labels: bug
